name: Run News Scraper (Google & Yahoo)

on:
  schedule:
    # ✅ JSTで15分ごとに実行するよう変更
    - cron: '*/15 * * * *' 
  
  workflow_dispatch: 
    # ✅ JSTで15分おき
    - cron: '*/15 * * * *'
    # ✅ JSTで毎時0分（1時間おき）
    - cron: '0 * * * *'
    # ✅ JSTで毎日15:00（→UTCでは06:00）
    - cron: '0 6 * * *'

  workflow_dispatch:

jobs:
  scrape-news:
    runs-on: ubuntu-latest 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' 
        python-version: '3.9'

    - name: Install dependencies
      run: |
